"""rename_description_to_remarks_in_rfi_table

Revision ID: 92a3ad98adc3
Revises: f8bdc1c42d18
Create Date: 2025-05-03 22:32:01.750421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a3ad98adc3'
down_revision = 'f8bdc1c42d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE rfi RENAME COLUMN description TO remarks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE rfi RENAME COLUMN remarks TO description')
    # ### end Alembic commands ###
