"""remove drawing_number column

Revision ID: cb895f09df66
Revises: f0ca2fc1d4e6
Create Date: 2025-05-03 14:00:46.060104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb895f09df66'
down_revision = 'f0ca2fc1d4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.drop_column('drawing_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawing_number', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
