"""Add drawing_title and issue_date to Drawing model

Revision ID: f0ca2fc1d4e6
Revises: 
Create Date: 2025-05-03 13:49:26.448192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ca2fc1d4e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawing_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.drop_column('issue_date')
        batch_op.drop_column('drawing_title')

    # ### end Alembic commands ###
